  ENV['S3_ACCESS_KEY_DEVELOPMENT'] = 'AKIAI5BZBAWX5ZCRHRUA'
  ENV['S3_SECRET_KEY_DEVELOPMENT'] = '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'
  ENV['S3_BUCKET_DEVELOPMENT'] = 'telltale-artwork-development'
